// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOJwfj5an0BTKiBqkIbazVgGyXREmdIw',
    appId: '1:966728588666:web:4e5ca291c6ea7ff6978ac3',
    messagingSenderId: '966728588666',
    projectId: 'the-chatter-8d84f',
    authDomain: 'the-chatter-8d84f.firebaseapp.com',
    storageBucket: 'the-chatter-8d84f.appspot.com',
    measurementId: 'G-QEMNR1PHDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXwK6YnzKmRmdRVrIub7QlbliCk561UQ',
    appId: '1:966728588666:android:4d3f2aa2c5f8d244978ac3',
    messagingSenderId: '966728588666',
    projectId: 'the-chatter-8d84f',
    storageBucket: 'the-chatter-8d84f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAic7yolFNlbJk1QHKxoeJvYgDWdniltcs',
    appId: '1:966728588666:ios:2b4eed19ec1844a4978ac3',
    messagingSenderId: '966728588666',
    projectId: 'the-chatter-8d84f',
    storageBucket: 'the-chatter-8d84f.appspot.com',
    androidClientId: '966728588666-99c4s7q0k7j45o8c4t07d8fimibegc76.apps.googleusercontent.com',
    iosClientId: '966728588666-r6so4fhrmqt6c6gn4gukbofo6ra8kkp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mithcKokoChatApp',
  );
}
